# Generated by Django 3.0.6 on 2020-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comm_images',
            field=models.ImageField(blank=True, upload_to='comment_pics'),
        ),
    ]
