# Generated by Django 3.0.6 on 2020-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_comm_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comm_images',
            field=models.ImageField(blank=True, upload_to='comment_images'),
        ),
    ]
