# Generated by Django 3.0.8 on 2020-07-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200717_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CCTV Cameras', 'CCTV Cameras'), ('Politics', 'Politics'), ('History', 'History'), ('General News', 'General News'), ('Technology', 'Technology'), ('Gaming', 'Gaming')], max_length=255, null=True),
        ),
    ]
